main.name = "CyberCat"
main.lang = "en"
main.whitelist = [
  "EXAMPLE_NETWORK"
]
main.plugins.grid.enabled = true
main.plugins.grid.report = true
main.plugins.grid.exclude = [
  "YourHomeNetworkHere"
]

ui.display.enabled = true
ui.display.type = "waveshare_4"
ui.display.color = "white"

ui.web.username = "admin"
ui.web.password = "admin"
ui.web.enabled = true
ui.web.address = "0.0.0.0"
ui.web.origin = ""
ui.web.port = 9000
ui.web.on_frame = ""

